add first structure
HumeniukNazar/Team-project-23group pull request #1
Opened 2024-05-01 17:37 UTC by RamiiaHolomoza

test

2024-05-01 17:41 UTC, HumeniukNazar requested changes
need container in html

2024-05-02 06:30 UTC, HumeniukNazar commented on src/css/hero.css
> +    font-family: var(--font-family);
щоб не писати font family 2 рази чи не краще назвати шрифт в root одразу Gilroy? Тут всюди один шрифт

2024-05-02 08:33 UTC, HumeniukNazar commented on src/css/hero.css
> +    line-height: 129%;
line-height ми будемо прописувати у відсотках? на лекціях викладач казав що краще ніби в одиниці переводити

2024-05-02 08:54 UTC, HumeniukNazar commented on src/css/hero.css
> +        height: auto;
тут рядок з висотою нічого не дає

2024-05-02 13:33 UTC, RamiiaHolomoza commented on src/css/hero.css
> +    font-family: var(--font-family);
Та в принципі без різниці, просто якщо буде декілька шрифтів то краще щоб було так
Ну ми можему тут і поміняти

2024-05-02 13:36 UTC, RamiiaHolomoza commented on src/css/hero.css
> +    line-height: 129%;
Знову таки . Якщо є зміни в проєкті то краще відсокти бо само порахує.  Можу поміняти якщо то критично

2024-05-03 11:19 UTC, HumeniukNazar approved these changes

2024-05-03 11:20 UTC, merged