Kurilov header
HumeniukNazar/Team-project-23group pull request #13
Opened 2024-05-03 09:13 UTC by Serhii-Kurilov

2024-05-03 10:52 UTC, HumeniukNazar commented on src/css/header.css
> -.container {
в десктопній версії хедер не відцентровано

2024-05-03 14:19 UTC, Serhii-Kurilov commented
Виправлено, також виставив позицію хедеру fixed

2024-05-04 13:23 UTC, HumeniukNazar requested changes
Відправив відео з фідбеком

2024-05-05 21:28 UTC, HumeniukNazar approved these changes

2024-05-05 21:28 UTC, merged